import { useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { ausenciasApi } from '../api/ausencias-api'

export function AusenciasList() {
  const client = useQueryClient(); const { data, isLoading } = useQuery({ queryKey: ['ausencias'], queryFn: ausenciasApi.listar }); const crear = useMutation({ mutationFn: ausenciasApi.crear, onSuccess: () => client.invalidateQueries({ queryKey: ['ausencias'] }) }); const resolver = useMutation({ mutationFn: ({ id, estado }: { id: number; estado: 'aprobada' | 'rechazada' }) => ausenciasApi.resolver(id, estado, ''), onSuccess: () => client.invalidateQueries({ queryKey: ['ausencias'] }) })
  const [form, setForm] = useState({ tipo: 'licencia_medica', desde: '', hasta: '', motivo: '', documento: undefined as File | undefined })
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await crear.mutateAsync(form); setForm({ tipo: 'licencia_medica', desde: '', hasta: '', motivo: '', documento: undefined }) }
  return <div className="space-y-5"><div><p className="text-sm font-medium text-amber-600">Personal</p><h1 className="mt-1 text-2xl font-semibold text-ink-900">Asistencias y ausencias</h1><p className="mt-1 text-sm text-ink-500">Registra licencias, permisos y documentos para revisión administrativa.</p></div><Card><form className="grid gap-4 sm:grid-cols-2" onSubmit={submit}><select value={form.tipo} onChange={(event) => setForm({ ...form, tipo: event.target.value })} className="rounded-md border border-ink-200 px-3 py-2"><option value="licencia_medica">Licencia médica</option><option value="permiso">Permiso</option><option value="vacaciones">Vacaciones</option><option value="inasistencia_justificada">Inasistencia justificada</option></select><input required type="date" value={form.desde} onChange={(event) => setForm({ ...form, desde: event.target.value })} className="rounded-md border border-ink-200 px-3 py-2" /><input required type="date" value={form.hasta} onChange={(event) => setForm({ ...form, hasta: event.target.value })} className="rounded-md border border-ink-200 px-3 py-2" /><input required placeholder="Motivo" value={form.motivo} onChange={(event) => setForm({ ...form, motivo: event.target.value })} className="rounded-md border border-ink-200 px-3 py-2" /><input type="file" accept="application/pdf,image/jpeg,image/png" onChange={(event) => setForm({ ...form, documento: event.target.files?.[0] })} className="text-sm" /><Button type="submit" disabled={crear.isPending}>Enviar solicitud</Button></form></Card>{isLoading && <p className="text-sm text-ink-500">Cargando solicitudes...</p>}{data?.map((item) => <Card key={item.id} className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-ink-900">{item.usuario?.name ?? 'Mi solicitud'} · {item.tipo}</p><p className="text-sm text-ink-500">{item.desde} al {item.hasta} · {item.motivo}</p><p className="text-xs text-ink-400">Estado: {item.estado}{item.documento_path ? ' · Documento adjunto' : ''}</p></div>{item.estado === 'pendiente' && item.usuario?.name !== undefined && <div className="flex gap-2"><Button variant="secondary" onClick={() => resolver.mutate({ id: item.id, estado: 'aprobada' })}>Aprobar</Button><Button variant="danger" onClick={() => resolver.mutate({ id: item.id, estado: 'rechazada' })}>Rechazar</Button></div>}</Card>)}</div>
}